export const TRANSACTION_OPEN = 'TRANSACTION_OPEN'
export const TRANSACTION_DELETE = 'TRANSACTION_DELETE'
export const TRANSACTION_RESTORE = 'TRANSACTION_RESTORE'
export const TRANSACTION_APPLY_CHANGES = 'TRANSACTION_APPLY_CHANGES'
export const TRANSACTION_FULL_DELETE = 'TRANSACTION_FULL_DELETE'

export const FILTER_SET_CONDITION = 'FILTER_SET_CONDITION'
export const FILTER_SET_TAGS = 'FILTER_SET_TAGS'
export const FILTER_ADD_TAG = 'FILTER_ADD_TAG'
export const FILTER_REMOVE_TAG = 'FILTER_ADD_TAG'
export const FILTER_RESET_CONDITION = 'FILTER_RESET_CONDITION'
export const FILTER_RESET_ALL = 'FILTER_RESET_ALL'

export const UPDATE_DATA = 'UPDATE_DATA'

export const MERGE_SERVER_DATA = 'MERGE_SERVER_DATA'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_LOCAL_STATE = 'SET_LOCAL_STATE'
// export const INIT_STATE = 'INIT_STATE'
