import {
  clampChroma,
  formatOklch,
  oklchToRgb,
  parseColor,
} from '@/6-shared/helpers/color'

/** Color calculations for dynamic user-authored colours. The static theme is
 * generated by ColorScale; these remain for tag colours and similar runtime
 * values.
 *
 * `alpha` *replaces* a colour's alpha rather than multiplying it, which is why
 * the state fills built on `action.selected` — itself already transparent —
 * come out at the opacity they name and not at a fraction of it. Only one of
 * the two CSS spellings does the same: `rgb(from C r g b / a)` replaces, and
 * `color-mix(in srgb, C a%, transparent)` multiplies. */

type Rgb = [red: number, green: number, blue: number]

/** Accepts every notation a color value can arrive in — `#rgb`, `#rrggbb`,
 * `rgb(…)`, `rgba(…)` and `oklch(…)` — by way of the one parser in
 * `helpers/color`. A second parser here is how `oklch()` came back as
 * `rgba(0.53, undefined, undefined, …)` and a luminance of `NaN`, silently:
 * the old one read an `oklch(L C H)` as a comma-separated triple and found
 * one number where it wanted three. */
function toRgb(color: string): Rgb {
  /* Chroma is clamped, not the channels clipped, so a wide-gamut value has an
     sRGB answer at the lightness it was authored at — which is the half of it
     that luminance is about. */
  const { r, g, b } = oklchToRgb(clampChroma(parseColor(color), 'srgb'))
  return [r * 255, g * 255, b * 255]
}

/** Replaces a colour's alpha **in the notation it arrived in**. An sRGB value
 * comes back as `rgba()` and an OKLCh one as `oklch(… / a)`, so a state fill
 * built on a wide-gamut palette value does not quietly fall back to sRGB on
 * its way through here. */
export function alpha(color: string, value: number): string {
  const clamped = Math.min(1, Math.max(0, value))
  const parsed = parseColor(color)

  if (color.trimStart().startsWith('oklch')) {
    return formatOklch({ ...parsed, alpha: clamped })
  }

  const [r, g, b] = toRgb(color)
  return `rgba(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)}, ${clamped})`
}

/** W3C relative luminance, rounded to three decimals because the third decimal
 * is what decides a colour sitting on the contrast threshold. */
export function getLuminance(color: string): number {
  const channels = toRgb(color).map(channel => {
    const value = channel / 255
    return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4
  })
  return Number(
    (
      0.2126 * channels[0] +
      0.7152 * channels[1] +
      0.0722 * channels[2]
    ).toFixed(3)
  )
}

export function getContrastRatio(foreground: string, background: string) {
  const a = getLuminance(foreground)
  const b = getLuminance(background)
  return (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05)
}

/** White or near-black over a background, at a contrast threshold of 3. This
 * is for dynamic colors, especially tag colors; static theme pairings are
 * authored in `colors.ts`. */
export function getContrastText(background: string): string {
  return getContrastRatio(background, '#fff') >= 3
    ? '#fff'
    : 'rgba(0, 0, 0, 0.87)'
}
