import type { TMeta } from './output'
import { success } from './output'

const commands = [
  {
    name: 'help',
    effect: 'none',
    required: [],
    optional: [],
    example: 'pnpm zerro -- help',
    successShape: 'commandManifest',
    errors: [],
  },
  {
    name: 'status',
    effect: 'none',
    required: [],
    optional: [],
    example: 'pnpm zerro -- status',
    successShape: 'localStatus',
    errors: ['INVALID_STATE', 'ENDPOINT_MISMATCH'],
  },
  {
    name: 'refresh',
    effect: 'local',
    required: ['ZERRO_TOKEN'],
    optional: [],
    example: 'ZERRO_TOKEN=... pnpm zerro -- refresh',
    successShape: 'refreshReceipt',
    errors: [
      'TOKEN_REQUIRED',
      'NETWORK_FAILURE',
      'ZENMONEY_REJECTED',
      'INVALID_ZENMONEY_RESPONSE',
      'INVALID_STATE',
    ],
  },
  {
    name: 'sync',
    effect: 'remote',
    required: ['ZERRO_TOKEN when outbox is non-empty'],
    optional: [],
    example: 'ZERRO_TOKEN=... pnpm zerro -- sync',
    successShape: 'syncReceipt',
    errors: [
      'TOKEN_REQUIRED',
      'NETWORK_FAILURE',
      'ZENMONEY_REJECTED',
      'INVALID_ZENMONEY_RESPONSE',
      'OUTBOX_NO_TRANSPORT',
      'INVALID_STATE',
    ],
  },
  {
    name: 'accounts list',
    effect: 'none',
    required: [],
    optional: ['--limit', '--cursor'],
    example: 'pnpm zerro -- accounts list --limit 50',
    successShape: 'accountPage',
    errors: ['INVALID_INPUT', 'INVALID_CURSOR', 'INVALID_STATE'],
  },
  {
    name: 'tags search',
    effect: 'none',
    required: [],
    optional: ['--query', '--limit', '--cursor'],
    example: 'pnpm zerro -- tags search --query food',
    successShape: 'tagPage',
    errors: ['INVALID_INPUT', 'INVALID_CURSOR', 'INVALID_STATE'],
  },
  {
    name: 'merchants search',
    effect: 'none',
    required: [],
    optional: ['--query', '--limit', '--cursor'],
    example: 'pnpm zerro -- merchants search --query amazon',
    successShape: 'merchantPage',
    errors: ['INVALID_INPUT', 'INVALID_CURSOR', 'INVALID_STATE'],
  },
  {
    name: 'transactions search',
    effect: 'none',
    required: [],
    optional: ['--query', '--from', '--to', '--account', '--limit', '--cursor'],
    example:
      'pnpm zerro -- transactions search --from 2026-07-01 --to 2026-07-31',
    successShape: 'transactionPage',
    errors: [
      'INVALID_INPUT',
      'ENTITY_NOT_FOUND',
      'INVALID_CURSOR',
      'INVALID_STATE',
    ],
  },
  {
    name: 'month get',
    effect: 'none',
    required: ['month'],
    optional: [],
    example: 'pnpm zerro -- month get 2026-07',
    successShape: 'monthSummary',
    errors: [
      'INVALID_INPUT',
      'STATE_NOT_INITIALIZED',
      'MONTH_NOT_FOUND',
      'INVALID_STATE',
    ],
  },
  {
    name: 'envelopes list',
    effect: 'none',
    required: ['--month'],
    optional: ['--query', '--limit', '--cursor'],
    example: 'pnpm zerro -- envelopes list --month 2026-07',
    successShape: 'envelopePage',
    errors: [
      'INVALID_INPUT',
      'STATE_NOT_INITIALIZED',
      'MONTH_NOT_FOUND',
      'INVALID_CURSOR',
      'INVALID_STATE',
    ],
  },
  {
    name: 'envelopes get',
    effect: 'none',
    required: ['envelopeId', '--month'],
    optional: [],
    example: 'pnpm zerro -- envelopes get tag#food --month 2026-07',
    successShape: 'envelope',
    errors: [
      'INVALID_INPUT',
      'STATE_NOT_INITIALIZED',
      'ENTITY_NOT_FOUND',
      'MONTH_NOT_FOUND',
      'INVALID_STATE',
    ],
  },
  {
    name: 'goals list',
    effect: 'none',
    required: ['--month'],
    optional: ['--query', '--limit', '--cursor'],
    example: 'pnpm zerro -- goals list --month 2026-07',
    successShape: 'goalPage',
    errors: [
      'INVALID_INPUT',
      'STATE_NOT_INITIALIZED',
      'MONTH_NOT_FOUND',
      'INVALID_CURSOR',
      'INVALID_STATE',
    ],
  },
  {
    name: 'debtors list',
    effect: 'none',
    required: [],
    optional: ['--query', '--limit', '--cursor'],
    example: 'pnpm zerro -- debtors list --limit 50',
    successShape: 'debtorPage',
    errors: [
      'INVALID_INPUT',
      'STATE_NOT_INITIALIZED',
      'INVALID_CURSOR',
      'INVALID_STATE',
    ],
  },
  {
    name: 'budget preview-set',
    effect: 'none',
    required: ['--input'],
    optional: [],
    example: 'pnpm zerro -- budget preview-set --input budgets.json',
    successShape: 'budgetPreview',
    errors: [
      'INVALID_INPUT',
      'INPUT_READ_FAILED',
      'STATE_NOT_INITIALIZED',
      'MONTH_NOT_FOUND',
      'ENTITY_NOT_FOUND',
      'CURRENCY_MISMATCH',
      'NO_CHANGES',
      'INVALID_STATE',
    ],
  },
  {
    name: 'budget stage-set',
    effect: 'local',
    required: ['--request-id', '--input'],
    optional: [],
    example:
      'pnpm zerro -- budget stage-set --request-id july-food-1 --input budgets.json',
    successShape: 'budgetStageReceipt',
    errors: [
      'INVALID_REQUEST_ID',
      'INVALID_INPUT',
      'INPUT_READ_FAILED',
      'IDEMPOTENCY_CONFLICT',
      'STATE_NOT_INITIALIZED',
      'MONTH_NOT_FOUND',
      'ENTITY_NOT_FOUND',
      'CURRENCY_MISMATCH',
      'NO_CHANGES',
      'STATE_WRITE_FAILED',
      'INVALID_STATE',
    ],
  },
  {
    name: 'outbox list',
    effect: 'none',
    required: [],
    optional: ['--limit', '--cursor'],
    example: 'pnpm zerro -- outbox list',
    successShape: 'outboxPage',
    errors: ['INVALID_INPUT', 'INVALID_CURSOR', 'INVALID_STATE'],
  },
  {
    name: 'outbox undo',
    effect: 'local',
    required: ['--request-id'],
    optional: [],
    example: 'pnpm zerro -- outbox undo --request-id undo-july-food-1',
    successShape: 'undoReceipt',
    errors: [
      'INVALID_REQUEST_ID',
      'IDEMPOTENCY_CONFLICT',
      'OUTBOX_EMPTY',
      'STATE_WRITE_FAILED',
      'INVALID_STATE',
    ],
  },
  {
    name: 'transaction preview-create',
    effect: 'none',
    required: ['--input'],
    optional: [],
    example: 'pnpm zerro -- transaction preview-create --input expense.json',
    successShape: 'transactionPreview',
    errors: [
      'INVALID_INPUT',
      'INPUT_READ_FAILED',
      'STATE_NOT_INITIALIZED',
      'ENTITY_NOT_FOUND',
      'INVALID_STATE',
    ],
  },
  {
    name: 'transaction stage-create',
    effect: 'local',
    required: ['--request-id', '--input'],
    optional: [],
    example:
      'pnpm zerro -- transaction stage-create --request-id groceries-1 --input expense.json',
    successShape: 'transactionStageReceipt',
    errors: [
      'INVALID_REQUEST_ID',
      'INVALID_INPUT',
      'INPUT_READ_FAILED',
      'IDEMPOTENCY_CONFLICT',
      'STATE_NOT_INITIALIZED',
      'ENTITY_NOT_FOUND',
      'STATE_WRITE_FAILED',
      'INVALID_STATE',
    ],
  },
] as const

export function getHelp(meta: TMeta) {
  return success('help', 'none', meta, {
    commands,
    defaults: { limit: 50, maximumLimit: 200 },
  })
}
